server:
  port: 80

eureka:
  client:
    #表示是否将自己注册进eurekaServer，默认true
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#设置feign客户端超时时间，（openFeign默认支持rebben）
ribbon:
  #指的是建立连接所用的时间，适用于网络环境正常的情况，两端链接所用的时间
  Readtimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    #feign日志以什么级别监控哪个类
    com.allen.cloud.service.PaymentFeignService: debug